//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace agTetribricks.TbScoreService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TbScore", Namespace="http://schemas.datacontract.org/2004/07/agTetribricksWeb", IsReference=true)]
    public partial class TbScore : agTetribricks.TbScoreService.EntityObject {
        
        private string EmailAddressField;
        
        private System.Guid IDField;
        
        private System.Nullable<System.DateTime> ScoreDateField;
        
        private System.Nullable<int> ScoreValueField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ScoreDate {
            get {
                return this.ScoreDateField;
            }
            set {
                if ((this.ScoreDateField.Equals(value) != true)) {
                    this.ScoreDateField = value;
                    this.RaisePropertyChanged("ScoreDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ScoreValue {
            get {
                return this.ScoreValueField;
            }
            set {
                if ((this.ScoreValueField.Equals(value) != true)) {
                    this.ScoreValueField = value;
                    this.RaisePropertyChanged("ScoreValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(agTetribricks.TbScoreService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(agTetribricks.TbScoreService.TbScore))]
    public partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(agTetribricks.TbScoreService.TbScore))]
    public partial class EntityObject : agTetribricks.TbScoreService.StructuralObject {
        
        private agTetribricks.TbScoreService.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public agTetribricks.TbScoreService.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EntityContainerNameField;
        
        private System.Collections.ObjectModel.ObservableCollection<agTetribricks.TbScoreService.EntityKeyMember> EntityKeyValuesField;
        
        private string EntitySetNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<agTetribricks.TbScoreService.EntityKeyMember> EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(agTetribricks.TbScoreService.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<agTetribricks.TbScoreService.EntityKeyMember>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(agTetribricks.TbScoreService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(agTetribricks.TbScoreService.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<agTetribricks.TbScoreService.TbScore>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(agTetribricks.TbScoreService.TbScore))]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string KeyField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.hosca.com/tetribricks", ConfigurationName="TbScoreService.ScoreService")]
    public interface ScoreService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.hosca.com/tetribricks/ScoreService/GetLatestScores", ReplyAction="http://www.hosca.com/tetribricks/ScoreService/GetLatestScoresResponse")]
        System.IAsyncResult BeginGetLatestScores(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<agTetribricks.TbScoreService.TbScore> EndGetLatestScores(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.hosca.com/tetribricks/ScoreService/SaveScore", ReplyAction="http://www.hosca.com/tetribricks/ScoreService/SaveScoreResponse")]
        System.IAsyncResult BeginSaveScore(agTetribricks.TbScoreService.TbScore score, System.AsyncCallback callback, object asyncState);
        
        void EndSaveScore(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ScoreServiceChannel : agTetribricks.TbScoreService.ScoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLatestScoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLatestScoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<agTetribricks.TbScoreService.TbScore> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<agTetribricks.TbScoreService.TbScore>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScoreServiceClient : System.ServiceModel.ClientBase<agTetribricks.TbScoreService.ScoreService>, agTetribricks.TbScoreService.ScoreService {
        
        private BeginOperationDelegate onBeginGetLatestScoresDelegate;
        
        private EndOperationDelegate onEndGetLatestScoresDelegate;
        
        private System.Threading.SendOrPostCallback onGetLatestScoresCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveScoreDelegate;
        
        private EndOperationDelegate onEndSaveScoreDelegate;
        
        private System.Threading.SendOrPostCallback onSaveScoreCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ScoreServiceClient() {
        }
        
        public ScoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetLatestScoresCompletedEventArgs> GetLatestScoresCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SaveScoreCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult agTetribricks.TbScoreService.ScoreService.BeginGetLatestScores(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLatestScores(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<agTetribricks.TbScoreService.TbScore> agTetribricks.TbScoreService.ScoreService.EndGetLatestScores(System.IAsyncResult result) {
            return base.Channel.EndGetLatestScores(result);
        }
        
        private System.IAsyncResult OnBeginGetLatestScores(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((agTetribricks.TbScoreService.ScoreService)(this)).BeginGetLatestScores(callback, asyncState);
        }
        
        private object[] OnEndGetLatestScores(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<agTetribricks.TbScoreService.TbScore> retVal = ((agTetribricks.TbScoreService.ScoreService)(this)).EndGetLatestScores(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLatestScoresCompleted(object state) {
            if ((this.GetLatestScoresCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLatestScoresCompleted(this, new GetLatestScoresCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLatestScoresAsync() {
            this.GetLatestScoresAsync(null);
        }
        
        public void GetLatestScoresAsync(object userState) {
            if ((this.onBeginGetLatestScoresDelegate == null)) {
                this.onBeginGetLatestScoresDelegate = new BeginOperationDelegate(this.OnBeginGetLatestScores);
            }
            if ((this.onEndGetLatestScoresDelegate == null)) {
                this.onEndGetLatestScoresDelegate = new EndOperationDelegate(this.OnEndGetLatestScores);
            }
            if ((this.onGetLatestScoresCompletedDelegate == null)) {
                this.onGetLatestScoresCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLatestScoresCompleted);
            }
            base.InvokeAsync(this.onBeginGetLatestScoresDelegate, null, this.onEndGetLatestScoresDelegate, this.onGetLatestScoresCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult agTetribricks.TbScoreService.ScoreService.BeginSaveScore(agTetribricks.TbScoreService.TbScore score, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveScore(score, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void agTetribricks.TbScoreService.ScoreService.EndSaveScore(System.IAsyncResult result) {
            base.Channel.EndSaveScore(result);
        }
        
        private System.IAsyncResult OnBeginSaveScore(object[] inValues, System.AsyncCallback callback, object asyncState) {
            agTetribricks.TbScoreService.TbScore score = ((agTetribricks.TbScoreService.TbScore)(inValues[0]));
            return ((agTetribricks.TbScoreService.ScoreService)(this)).BeginSaveScore(score, callback, asyncState);
        }
        
        private object[] OnEndSaveScore(System.IAsyncResult result) {
            ((agTetribricks.TbScoreService.ScoreService)(this)).EndSaveScore(result);
            return null;
        }
        
        private void OnSaveScoreCompleted(object state) {
            if ((this.SaveScoreCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveScoreCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveScoreAsync(agTetribricks.TbScoreService.TbScore score) {
            this.SaveScoreAsync(score, null);
        }
        
        public void SaveScoreAsync(agTetribricks.TbScoreService.TbScore score, object userState) {
            if ((this.onBeginSaveScoreDelegate == null)) {
                this.onBeginSaveScoreDelegate = new BeginOperationDelegate(this.OnBeginSaveScore);
            }
            if ((this.onEndSaveScoreDelegate == null)) {
                this.onEndSaveScoreDelegate = new EndOperationDelegate(this.OnEndSaveScore);
            }
            if ((this.onSaveScoreCompletedDelegate == null)) {
                this.onSaveScoreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveScoreCompleted);
            }
            base.InvokeAsync(this.onBeginSaveScoreDelegate, new object[] {
                        score}, this.onEndSaveScoreDelegate, this.onSaveScoreCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override agTetribricks.TbScoreService.ScoreService CreateChannel() {
            return new ScoreServiceClientChannel(this);
        }
        
        private class ScoreServiceClientChannel : ChannelBase<agTetribricks.TbScoreService.ScoreService>, agTetribricks.TbScoreService.ScoreService {
            
            public ScoreServiceClientChannel(System.ServiceModel.ClientBase<agTetribricks.TbScoreService.ScoreService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetLatestScores(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetLatestScores", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<agTetribricks.TbScoreService.TbScore> EndGetLatestScores(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<agTetribricks.TbScoreService.TbScore> _result = ((System.Collections.ObjectModel.ObservableCollection<agTetribricks.TbScoreService.TbScore>)(base.EndInvoke("GetLatestScores", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveScore(agTetribricks.TbScoreService.TbScore score, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = score;
                System.IAsyncResult _result = base.BeginInvoke("SaveScore", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSaveScore(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SaveScore", _args, result);
            }
        }
    }
}
